@base_url = http://localhost:5093

GET {{base_url}}

###

GET {{base_url}}/api/pets
Accept: application/json

###
POST {{base_url}}/api/pets
Content-Type: application/json

{
  "Name": "Buddy",
  "Breed": {
    "Name": "Golden Retriever",
    "CommonName": "Golden",
    "Description": "Friendly, intelligent, and devoted."
  },
  "Color": {
    "GeneralColor": "Golden",
    "Body": "Light golden",
    "Face": "Cream",
    "Legs": "Golden",
    "Tail": "Golden"
  },
  "Weight": 30.5,
  "BirthDate": "2022-06-15"
}
